/* eslint-disable */
/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */
import { HTMLStencilElement, JSXBase } from "@stencil/core/internal";
import { NewsLoader } from "./components/honey-news/news/NewsLoader";
import { NewsOptions } from "./components/honey-news/news/NewsOptions";
import { StatisticOptions } from "./components/honey-news/statistic/StatisticOptions";
export namespace Components {
    interface HoneyDisclaimer {
    }
    interface HoneyDisclaimerBootstrap {
    }
    interface HoneyDisclaimerPapercss {
    }
    interface HoneyNews {
        /**
          * Feeds Administration Komponente
         */
        "feedAdministration": HTMLHoneyNewsFeedsElement;
        /**
          * base of local site
         */
        "localBasePath": any;
        /**
          * News reader Komponente
         */
        "newsFeed": HTMLHoneyNewsFeedElement;
        /**
          * base of remote site
         */
        "siteBasePath": any;
        /**
          * enable console logging
         */
        "verbose": boolean;
    }
    interface HoneyNewsFeed {
        /**
          * Hilfsklasse zum Laden der Daten
         */
        "feedLoader": NewsLoader;
        /**
          * Update honey-news options
          * @param options : NewsOptions plain object to set the options
         */
        "updateOptions": (options: NewsOptions) => Promise<void>;
        /**
          * enable console logging
         */
        "verbose": boolean;
    }
    interface HoneyNewsFeeds {
        /**
          * Hilfsklasse zum Laden der Daten
         */
        "feedLoader": NewsLoader;
    }
    interface HoneyNewsHeader {
    }
    interface HoneyNewsStatistic {
        /**
          * Update statistic options
          * @param options : NewsOptions plain object to set the options
         */
        "updateOptions": (options: StatisticOptions) => Promise<void>;
        /**
          * enable console logging
         */
        "verbose": boolean;
    }
    interface HoneyStyledComponent {
        /**
          * themepostfix of theme name e.g. style when honey-papercss-style
         */
        "themepostfix": string;
        /**
          * themeprefix of theme name e.g. honey when honey-papercss-style
         */
        "themeprefix": string;
    }
}
declare global {
    interface HTMLHoneyDisclaimerElement extends Components.HoneyDisclaimer, HTMLStencilElement {
    }
    var HTMLHoneyDisclaimerElement: {
        prototype: HTMLHoneyDisclaimerElement;
        new (): HTMLHoneyDisclaimerElement;
    };
    interface HTMLHoneyDisclaimerBootstrapElement extends Components.HoneyDisclaimerBootstrap, HTMLStencilElement {
    }
    var HTMLHoneyDisclaimerBootstrapElement: {
        prototype: HTMLHoneyDisclaimerBootstrapElement;
        new (): HTMLHoneyDisclaimerBootstrapElement;
    };
    interface HTMLHoneyDisclaimerPapercssElement extends Components.HoneyDisclaimerPapercss, HTMLStencilElement {
    }
    var HTMLHoneyDisclaimerPapercssElement: {
        prototype: HTMLHoneyDisclaimerPapercssElement;
        new (): HTMLHoneyDisclaimerPapercssElement;
    };
    interface HTMLHoneyNewsElement extends Components.HoneyNews, HTMLStencilElement {
    }
    var HTMLHoneyNewsElement: {
        prototype: HTMLHoneyNewsElement;
        new (): HTMLHoneyNewsElement;
    };
    interface HTMLHoneyNewsFeedElement extends Components.HoneyNewsFeed, HTMLStencilElement {
    }
    var HTMLHoneyNewsFeedElement: {
        prototype: HTMLHoneyNewsFeedElement;
        new (): HTMLHoneyNewsFeedElement;
    };
    interface HTMLHoneyNewsFeedsElement extends Components.HoneyNewsFeeds, HTMLStencilElement {
    }
    var HTMLHoneyNewsFeedsElement: {
        prototype: HTMLHoneyNewsFeedsElement;
        new (): HTMLHoneyNewsFeedsElement;
    };
    interface HTMLHoneyNewsHeaderElement extends Components.HoneyNewsHeader, HTMLStencilElement {
    }
    var HTMLHoneyNewsHeaderElement: {
        prototype: HTMLHoneyNewsHeaderElement;
        new (): HTMLHoneyNewsHeaderElement;
    };
    interface HTMLHoneyNewsStatisticElement extends Components.HoneyNewsStatistic, HTMLStencilElement {
    }
    var HTMLHoneyNewsStatisticElement: {
        prototype: HTMLHoneyNewsStatisticElement;
        new (): HTMLHoneyNewsStatisticElement;
    };
    interface HTMLHoneyStyledComponentElement extends Components.HoneyStyledComponent, HTMLStencilElement {
    }
    var HTMLHoneyStyledComponentElement: {
        prototype: HTMLHoneyStyledComponentElement;
        new (): HTMLHoneyStyledComponentElement;
    };
    interface HTMLElementTagNameMap {
        "honey-disclaimer": HTMLHoneyDisclaimerElement;
        "honey-disclaimer-bootstrap": HTMLHoneyDisclaimerBootstrapElement;
        "honey-disclaimer-papercss": HTMLHoneyDisclaimerPapercssElement;
        "honey-news": HTMLHoneyNewsElement;
        "honey-news-feed": HTMLHoneyNewsFeedElement;
        "honey-news-feeds": HTMLHoneyNewsFeedsElement;
        "honey-news-header": HTMLHoneyNewsHeaderElement;
        "honey-news-statistic": HTMLHoneyNewsStatisticElement;
        "honey-styled-component": HTMLHoneyStyledComponentElement;
    }
}
declare namespace LocalJSX {
    interface HoneyDisclaimer {
    }
    interface HoneyDisclaimerBootstrap {
    }
    interface HoneyDisclaimerPapercss {
    }
    interface HoneyNews {
        /**
          * Feeds Administration Komponente
         */
        "feedAdministration"?: HTMLHoneyNewsFeedsElement;
        /**
          * base of local site
         */
        "localBasePath"?: any;
        /**
          * News reader Komponente
         */
        "newsFeed"?: HTMLHoneyNewsFeedElement;
        /**
          * base of remote site
         */
        "siteBasePath"?: any;
        /**
          * enable console logging
         */
        "verbose"?: boolean;
    }
    interface HoneyNewsFeed {
        /**
          * Hilfsklasse zum Laden der Daten
         */
        "feedLoader"?: NewsLoader;
        /**
          * enable console logging
         */
        "verbose"?: boolean;
    }
    interface HoneyNewsFeeds {
        /**
          * Hilfsklasse zum Laden der Daten
         */
        "feedLoader"?: NewsLoader;
    }
    interface HoneyNewsHeader {
    }
    interface HoneyNewsStatistic {
        /**
          * enable console logging
         */
        "verbose"?: boolean;
    }
    interface HoneyStyledComponent {
        /**
          * themepostfix of theme name e.g. style when honey-papercss-style
         */
        "themepostfix"?: string;
        /**
          * themeprefix of theme name e.g. honey when honey-papercss-style
         */
        "themeprefix"?: string;
    }
    interface IntrinsicElements {
        "honey-disclaimer": HoneyDisclaimer;
        "honey-disclaimer-bootstrap": HoneyDisclaimerBootstrap;
        "honey-disclaimer-papercss": HoneyDisclaimerPapercss;
        "honey-news": HoneyNews;
        "honey-news-feed": HoneyNewsFeed;
        "honey-news-feeds": HoneyNewsFeeds;
        "honey-news-header": HoneyNewsHeader;
        "honey-news-statistic": HoneyNewsStatistic;
        "honey-styled-component": HoneyStyledComponent;
    }
}
export { LocalJSX as JSX };
declare module "@stencil/core" {
    export namespace JSX {
        interface IntrinsicElements {
            "honey-disclaimer": LocalJSX.HoneyDisclaimer & JSXBase.HTMLAttributes<HTMLHoneyDisclaimerElement>;
            "honey-disclaimer-bootstrap": LocalJSX.HoneyDisclaimerBootstrap & JSXBase.HTMLAttributes<HTMLHoneyDisclaimerBootstrapElement>;
            "honey-disclaimer-papercss": LocalJSX.HoneyDisclaimerPapercss & JSXBase.HTMLAttributes<HTMLHoneyDisclaimerPapercssElement>;
            "honey-news": LocalJSX.HoneyNews & JSXBase.HTMLAttributes<HTMLHoneyNewsElement>;
            "honey-news-feed": LocalJSX.HoneyNewsFeed & JSXBase.HTMLAttributes<HTMLHoneyNewsFeedElement>;
            "honey-news-feeds": LocalJSX.HoneyNewsFeeds & JSXBase.HTMLAttributes<HTMLHoneyNewsFeedsElement>;
            "honey-news-header": LocalJSX.HoneyNewsHeader & JSXBase.HTMLAttributes<HTMLHoneyNewsHeaderElement>;
            "honey-news-statistic": LocalJSX.HoneyNewsStatistic & JSXBase.HTMLAttributes<HTMLHoneyNewsStatisticElement>;
            "honey-styled-component": LocalJSX.HoneyStyledComponent & JSXBase.HTMLAttributes<HTMLHoneyStyledComponentElement>;
        }
    }
}
