name: Github CI

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [16.13.1]

    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
    - name: build
      run: |
        npm install
        npm run build --if-present
    - name: e2e tests (playwright)
      run: |
        npm start &
        sleep 10
        npx playwright test --grep-invert @local
        kill %1
      env:
        CI: true
    - name: cdc tests (pact-js)
      run: |
        npx jest .*.pact.ts
      env:
        CI: true
